export const SENTINEL = 'GENERATED by codex-bridge'
export const SIZE_LIMIT = 32768

export interface RuleAttrs {
  codexTargets: string[]
  description: string | null
}

function stripQuotes(value: string): string {
  return value.replace(/^['"]|['"]$/g, '').trim()
}

function parseAttrs(raw: string): RuleAttrs {
  const targets: string[] = []
  let description: string | null = null
  let inTargets = false
  for (const line of raw.split(/\r?\n/)) {
    const listMatch = line.match(/^\s*-\s+(.+?)\s*$/)
    if (inTargets && listMatch) {
      targets.push(stripQuotes(listMatch[1] ?? ''))
      continue
    }
    inTargets = false
    const kv = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/)
    if (!kv) continue
    const key = kv[1] ?? ''
    const value = (kv[2] ?? '').trim()
    if (key === 'codexTargets') {
      if (value.startsWith('[')) {
        const inner = value.slice(1, value.endsWith(']') ? -1 : value.length)
        for (const part of inner.split(',')) {
          const target = stripQuotes(part.trim())
          if (target) targets.push(target)
        }
      } else if (value === '') {
        inTargets = true
      }
    } else if (key === 'description') {
      description = value === '' ? null : stripQuotes(value)
    }
  }
  return { codexTargets: targets, description }
}

export function parseFrontmatter(content: string): { attrs: RuleAttrs; body: string } {
  const empty: RuleAttrs = { codexTargets: [], description: null }
  if (!content.startsWith('---\n') && !content.startsWith('---\r\n')) {
    return { attrs: empty, body: content }
  }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { attrs: empty, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).replace(/^\r?\n/, '')
  return { attrs: parseAttrs(raw), body }
}

export function renderAgentsFile(sources: string[], bodies: string[]): string {
  const header = `<!-- ${SENTINEL}. DO NOT EDIT.\n     Source: ${sources.join(', ')} -->`
  const merged = bodies.map((b) => b.trim()).join('\n\n')
  return `${header}\n\n${merged}\n`
}

export function hasSentinel(content: string): boolean {
  return content.includes(SENTINEL)
}
