import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

export const SENTINEL = 'GENERATED by codex-bridge'
export const SIZE_LIMIT = 32768

export interface RuleAttrs {
  codexTargets: string[]
  description: string | null
}

function stripQuotes(value: string): string {
  return value.replace(/^['"]|['"]$/g, '').trim()
}

function parseAttrs(raw: string): RuleAttrs {
  const targets: string[] = []
  let description: string | null = null
  let inTargets = false
  for (const line of raw.split(/\r?\n/)) {
    const listMatch = line.match(/^\s*-\s+(.+?)\s*$/)
    if (inTargets && listMatch) {
      targets.push(stripQuotes(listMatch[1] ?? ''))
      continue
    }
    inTargets = false
    const kv = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/)
    if (!kv) continue
    const key = kv[1] ?? ''
    const value = (kv[2] ?? '').trim()
    if (key === 'codexTargets') {
      if (value.startsWith('[')) {
        const inner = value.slice(1, value.endsWith(']') ? -1 : value.length)
        for (const part of inner.split(',')) {
          const target = stripQuotes(part.trim())
          if (target) targets.push(target)
        }
      } else if (value === '') {
        inTargets = true
      }
    } else if (key === 'description') {
      description = value === '' ? null : stripQuotes(value)
    }
  }
  return { codexTargets: targets, description }
}

export function parseFrontmatter(content: string): { attrs: RuleAttrs; body: string } {
  const empty: RuleAttrs = { codexTargets: [], description: null }
  if (!content.startsWith('---\n') && !content.startsWith('---\r\n')) {
    return { attrs: empty, body: content }
  }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { attrs: empty, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).replace(/^\r?\n/, '')
  return { attrs: parseAttrs(raw), body }
}

export function renderAgentsFile(sources: string[], bodies: string[]): string {
  const header = `<!-- ${SENTINEL}. DO NOT EDIT.\n     Source: ${sources.join(', ')} -->`
  const merged = bodies.map((b) => b.trim()).join('\n\n')
  return `${header}\n\n${merged}\n`
}

export function hasSentinel(content: string): boolean {
  return content.includes(SENTINEL)
}

export interface RuleInput {
  file: string
  targets: string[]
  body: string
}

export interface TargetGroup {
  target: string
  members: { file: string; body: string }[]
}

export function groupRulesByTarget(rules: RuleInput[]): { groups: TargetGroup[]; unmapped: string[] } {
  const byTarget = new Map<string, { file: string; body: string }[]>()
  const unmapped: string[] = []
  for (const rule of rules) {
    if (rule.targets.length === 0) {
      unmapped.push(rule.file)
      continue
    }
    for (const target of rule.targets) {
      const members = byTarget.get(target) ?? []
      members.push({ file: rule.file, body: rule.body })
      byTarget.set(target, members)
    }
  }
  const groups: TargetGroup[] = [...byTarget.keys()].sort().map((target) => ({
    target,
    members: (byTarget.get(target) ?? []).sort((a, b) => a.file.localeCompare(b.file)),
  }))
  return { groups, unmapped: unmapped.sort() }
}

export type WriteDecision = { action: 'write' } | { action: 'skip-handwritten' }

export function decideWrite(existing: string | null, _next: string): WriteDecision {
  if (existing === null) return { action: 'write' }
  if (hasSentinel(existing)) return { action: 'write' }
  return { action: 'skip-handwritten' }
}

export function checkSize(content: string, limit: number = SIZE_LIMIT): { ok: boolean; bytes: number } {
  const bytes = Buffer.byteLength(content, 'utf8')
  return { ok: bytes <= limit, bytes }
}

export interface PlannedOutput {
  path: string
  content: string
}

export interface CollectResult {
  outputs: PlannedOutput[]
  warnings: string[]
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await stat(target)
    return true
  } catch {
    return false
  }
}

export async function collectProjectOutputs(root: string): Promise<CollectResult> {
  const outputs: PlannedOutput[] = []
  const warnings: string[] = []

  const rulesDir = join(root, '.claude', 'rules')
  if (await pathExists(rulesDir)) {
    const entries = (await readdir(rulesDir)).filter((f) => f.endsWith('.md')).sort()
    const rules: RuleInput[] = []
    for (const file of entries) {
      const raw = await readFile(join(rulesDir, file), 'utf8')
      const { attrs, body } = parseFrontmatter(raw)
      rules.push({ file, targets: attrs.codexTargets, body })
    }
    const { groups, unmapped } = groupRulesByTarget(rules)
    for (const orphan of unmapped) {
      warnings.push(`未マッピング rule (codexTargets 無し): .claude/rules/${orphan}`)
    }
    for (const group of groups) {
      const targetDir = join(root, group.target)
      if (!(await pathExists(targetDir))) {
        warnings.push(`target ディレクトリが存在しないためスキップ: ${group.target}`)
        continue
      }
      const sources = group.members.map((m) => `.claude/rules/${m.file}`)
      const bodies = group.members.map((m) => m.body)
      outputs.push({ path: join(targetDir, 'AGENTS.md'), content: renderAgentsFile(sources, bodies) })
    }
  } else {
    warnings.push('.claude/rules ディレクトリが見つかりません')
  }

  const claudeMd = join(root, 'CLAUDE.md')
  if (await pathExists(claudeMd)) {
    const content = await readFile(claudeMd, 'utf8')
    outputs.push({ path: join(root, 'AGENTS.md'), content: renderAgentsFile(['CLAUDE.md'], [content]) })
  } else {
    warnings.push('root CLAUDE.md が見つかりません')
  }

  return { outputs, warnings }
}

export async function collectGlobalOutput(home: string): Promise<CollectResult> {
  const source = join(home, '.claude', 'CLAUDE.md')
  if (!(await pathExists(source))) {
    return { outputs: [], warnings: ['~/.claude/CLAUDE.md が見つかりません'] }
  }
  const content = await readFile(source, 'utf8')
  return {
    outputs: [
      { path: join(home, '.codex', 'AGENTS.md'), content: renderAgentsFile(['~/.claude/CLAUDE.md'], [content]) },
    ],
    warnings: [],
  }
}

export interface WriteReport {
  written: string[]
  skippedHandwritten: string[]
  oversize: { path: string; bytes: number }[]
}

export async function writeOutputs(outputs: PlannedOutput[]): Promise<WriteReport> {
  const report: WriteReport = { written: [], skippedHandwritten: [], oversize: [] }
  for (const output of outputs) {
    const existing = (await pathExists(output.path)) ? await readFile(output.path, 'utf8') : null
    if (decideWrite(existing, output.content).action === 'skip-handwritten') {
      report.skippedHandwritten.push(output.path)
      continue
    }
    await mkdir(dirname(output.path), { recursive: true })
    await writeFile(output.path, output.content)
    report.written.push(output.path)
    const size = checkSize(output.content)
    if (!size.ok) report.oversize.push({ path: output.path, bytes: size.bytes })
  }
  return report
}

export async function main(argv: string[], env: { cwd: string; home: string }): Promise<number> {
  const isGlobal = argv.includes('--global')
  const { outputs, warnings } = isGlobal ? await collectGlobalOutput(env.home) : await collectProjectOutputs(env.cwd)
  const report = await writeOutputs(outputs)

  console.log(`codex-bridge: ${isGlobal ? 'global' : 'project'} モードで実行`)
  for (const path of report.written) console.log(`  生成: ${path}`)
  for (const path of report.skippedHandwritten) console.log(`  スキップ(手書き): ${path}`)
  for (const item of report.oversize)
    console.log(`  警告(32KB 超過, 切り捨てリスク): ${item.path} = ${item.bytes} bytes`)
  for (const warning of warnings) console.log(`  警告: ${warning}`)
  console.log(
    `完了: ${report.written.length} 件生成 / ${report.skippedHandwritten.length} 件スキップ / ${warnings.length} 件警告`,
  )
  return 0
}
